//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCommunicator.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarData
    {
        public int ID { get; set; }
        public int CarInformationId { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> BatteryPercent { get; set; }
    
        public virtual CarInformation CarInformation { get; set; }
    }
}
