//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCommunicator.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInformation
    {
        public CarInformation()
        {
            this.CarData = new HashSet<CarData>();
        }
    
        public int ID { get; set; }
        public string Owner { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<CarData> CarData { get; set; }
    }
}
