//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCommunicator.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggerInformation
    {
        public int ID { get; set; }
        public Nullable<int> LoggerBaseId { get; set; }
        public string Message { get; set; }
        public int MessageType { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual LoggerBase LoggerBase { get; set; }
    }
}
